### ISSUE TITLE
Haze Model - Sensitivity to the reference wavelength

### ISSUE THREAD

**Issue by y-chachan** [ideasrule/platon#22]
Characterise the outcome of the retrieval for different reference wavelengths

**Comment by ideasrule** [comment]
@y-chachan Should we change the default reference wavelength to 500 nm?  People care about what the scattering is at 500 nm, but not at 1000 nm (because there basically isn't any).  Switching to 500 nm would make the scattering amplitude more intuitive--"scattering is this many times stronger than Rayleigh in the middle of STIS".
