### ISSUE TITLE
Retrievals consistently failing 'assert' in get_line_of_sight_tau

### ISSUE THREAD

**Issue by radicamc** [ideasrule/platon#45]
Hi,

I've been trying to run retrievals on some simulated data, and for certain input parameters, the nested sampling retrieval fails within the first couple of likelihood calls with the following error:

Traceback (most recent call last):
  File "/home/radica/.anaconda3/envs/astroconda/lib/python3.6/site-packages/dynesty/dynesty.py", line 939, in __call__
    return self.func(x, *self.args, **self.kwargs)
  File "/home/radica/.anaconda3/envs/astroconda/lib/python3.6/site-packages/platon/combined_retriever.py", line 379, in multinest_ln_like
    eclipse_depths, eclipse_errors)
  File "/home/radica/.anaconda3/envs/astroconda/lib/python3.6/site-packages/platon/combined_retriever.py", line 149, in _ln_like
    part_size=part_size, ri=ri, P_quench=P_quench, full_output=True)
  File "/home/radica/.anaconda3/envs/astroconda/lib/python3.6/site-packages/platon/transit_depth_calculator.py", line 286, in compute_depths
    radii)
  File "/home/radica/.anaconda3/envs/astroconda/lib/python3.6/site-packages/platon/_tau_calculator.py", line 23, in get_line_of_sight_tau
    assert(np.allclose(radii, np.sort(radii)[::-1]))
AssertionError

It seems to only occur when I add the planet radius or mass as a fit parameter. If I remove radius and mass as fittable parameters, but keep everything else the same, the retrieval will run to completion.

**Comment by radicamc** [comment]
I've also noticed that if I decrease the  'nlive' parameter to 100 from 1000, I can include one of Rp or Mp as a fittable parameter, but not both. And I can only use uniform prior ranges whichever one is included of 0.95*guess to 1.05*guess. If I extend these to 0.9*guess to 1.1*guess, the retrieval fails again with the same error as above. The mass/radius of the planet in question are 0.28M_jup and 1.27R_jup.

**Comment by ideasrule** [comment]
Hi radicamc,

This assertion usually gets thrown when the code fails to find a hydrostatic solution, which in turn happens when the atmosphere is too loosely bound.  My guess is that your priors for radius and mass are wide enough to cause PLATON to explore a low mass, high radius region of parameter space where no hydrostatic solution exists.  So I'd recommend shrinking the prior for radius as much as possible--for transiting planets, literature values should be enough to put very tight constraints.  Also put a prior on the temperature to make sure it doesn't get unreasonably hot, which leads to a puffy atmosphere.  The mass prior should ideally be a Gaussian with standard deviation corresponding to the measurement error, but if that causes the code to crash, try a uniform prior with narrow bounds.

Hope this helps!

**Comment by radicamc** [comment]
Hi, thanks for the input! in my case, shrinking the temperature prior range seems to have helped - nothing has failed in the first couple of hundred likelihood calls anyways. Perhaps a more helpful error message here would be a good feature. Most other errors I've gotten from PLATON have included a small sentence pointing me to the likely resolution. Something like that here would be a great addition in my opinion. 
Thanks again!
